pull_request_rules:
  - name: Automatic merge on CI
    conditions:
      - or:
        - base=main
        - base=dev
      - "status-success=lint"
      - "status-success=test"
      - "status-success=build"
      - "status-success=release"
    actions:
      merge:
        method: merge
queue_rules:
  - name: default
    queue_conditions:
      - check-success = test
