pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - status-success=test - test (ubuntu-latest, 3.11)
      - status-success=build - build
    actions:
      merge:
        method: merge
